food and storage class creation
bigliolimatteo/whats-in-my-fridge pull request #1
Opened 2024-12-18 17:05 UTC by laragazzadelsole

tvb <3

2024-12-20 11:04 UTC, bigliolimatteo requested changes
+ move code to specific folders, like `tests/`, `src/`, ...

+ use a formatter like [black](https://github.com/psf/black)

2024-12-20 11:04 UTC, bigliolimatteo commented on generic_food_storage.py
> +                self.capacity -= f.quantity
define aux function to reduce capacity so it can be reused

2024-12-20 11:04 UTC, bigliolimatteo commented on generic_food_storage.py
> +                return False
raise exception if I cannot add food

2024-12-20 11:04 UTC, bigliolimatteo commented on generic_food_storage.py
> +                return self.foods, self.capacity
why do you return foods/capacity?

2024-12-20 11:04 UTC, bigliolimatteo commented on generic_food_storage.py
> +            self.capacity += f.quantity
as above

2024-12-20 11:04 UTC, bigliolimatteo commented on generic_food_storage.py
> +            return self.foods, self.capacity
as above

2024-12-20 11:04 UTC, bigliolimatteo commented on generic_food_storage.py
> +    def food_availability(self, new_date):
typed input, so conversion is not needed

2024-12-20 11:04 UTC, bigliolimatteo commented on generic_food_storage.py
> +        for food in self.foods:
can be done in one liner, like `return [food for f in self.foods if food.expiration_date < ...]`

2024-12-20 11:04 UTC, bigliolimatteo commented on test.py
> +from generic_food import GenericFood
put in a specific folder, like `test/generic_food.py`, `test/generic_storage.py`

2024-12-20 11:04 UTC, bigliolimatteo commented on test.py
> +    #print(available_food)
remove comment from production code

2024-12-20 11:04 UTC, bigliolimatteo commented on test.py
> +    print(available_food)
printing is not a test, tests are done w `assert something == something_else`

2024-12-20 11:09 UTC, laragazzadelsole commented on .gitignore
> +.venv
Ok

2024-12-20 11:16 UTC, laragazzadelsole commented on generic_food.py
> +        self.quantity = quantity
Done

2024-12-20 11:20 UTC, laragazzadelsole commented on generic_food.py
> +        self.expiration_date = expiration_date
Generally I agree it shouldn't happen, however sometimes there are offers for things expiring on the same day or expired food can be purchased by mistake but it's still eatable. Is it ok to leave it as it is?

2024-12-20 11:22 UTC, laragazzadelsole commented on generic_food.py
> +        else:
Done

2024-12-20 11:24 UTC, laragazzadelsole commented on generic_food.py
> +        self.expiration_date = date.fromisoformat(expiration_date)
See 2 comments above

2024-12-20 16:41 UTC, laragazzadelsole commented on generic_food.py
> +    def __init__(self, name, purchase_date, expiration_date, quantity):
Ok

2024-12-23 09:24 UTC, laragazzadelsole commented on generic_food.py
> +        self.purchase_date = date.fromisoformat(purchase_date)
Done

2024-12-23 09:26 UTC, laragazzadelsole commented on generic_food.py
> +        if new_quantity is not None:
Done

2024-12-23 09:27 UTC, laragazzadelsole commented on generic_food_storage.py
> +    def __init__(self, name, capacity, foods):
Done

2024-12-23 09:28 UTC, laragazzadelsole commented on generic_food_storage.py
> +        self.capacity = capacity
Done

2024-12-23 11:04 UTC, laragazzadelsole commented on generic_food_storage.py
> +                self.capacity -= f.quantity
Done

2024-12-23 11:12 UTC, laragazzadelsole commented on generic_food_storage.py
> +                return False
Done

2024-12-23 11:13 UTC, laragazzadelsole commented on generic_food_storage.py
> +                return self.foods, self.capacity
I don't know

2024-12-23 11:13 UTC, laragazzadelsole commented on generic_food_storage.py
> +            self.capacity += f.quantity
I don't know

2024-12-23 11:14 UTC, laragazzadelsole commented on generic_food_storage.py
> +            return self.foods, self.capacity
I don't know

2024-12-23 11:14 UTC, laragazzadelsole commented on generic_food_storage.py
> +    def food_availability(self, new_date):
Done

2024-12-23 13:30 UTC, laragazzadelsole commented on generic_food_storage.py
> +        for food in self.foods:
Done

2024-12-23 13:33 UTC, laragazzadelsole commented on test.py
> +    #print(available_food)
Ok

2024-12-23 15:40 UTC, laragazzadelsole commented on test.py
> +    print(available_food)
Done

2025-01-20 19:36 UTC, bigliolimatteo commented on generic_food.py
> +        self.expiration_date = expiration_date
LGTM 🚀

2025-01-20 19:53 UTC, bigliolimatteo requested changes

2025-01-20 19:53 UTC, bigliolimatteo commented on requirements.txt
> +black==24.10.0
not needed

2025-01-20 19:53 UTC, bigliolimatteo commented on requirements.txt
> +click==8.1.8
are this all needed??

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food.py
> +class GenericFood:
this could maybe be a[ dataclass](https://peps.python.org/pep-0557/)

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food.py
> +        if expiration_date >= purchase_date:
I would maybe group the checks in some assert lines and then declare self.x = x all together at the end to reduce code lines

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food.py
> +    def modify_quantity(cls, new_quantity):
https://stackoverflow.com/questions/51079503/dataclasses-and-property-decorator

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food.py
> +        return food
why dont you just return directly the str?

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def __init__(self, name: str, capacity: float, foods: list):
food is a list of list[Food]

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def __init__(self, name: str, capacity: float, foods: list):
and capacity is int maybe? 🤔

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +        if capacity > 0:
what if capacity <0? 🤔  we instantiate a container wout capacity?

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def reduce_capacity(self, consumed_quantity):
https://stackoverflow.com/questions/51079503/dataclasses-and-property-decorator

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def add_food(self, new_food):
```suggestion
    def add_food(self, new_food: list[Food]):
```

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +        for f in new_food:
in this way some food will be accepted and some not :( check first if len(food)> capacity and then insert

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +                self.reduce_capacity(f.quantity)
reduce all at once

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def consume_food(self, consumed_food, consumed_quantity):
parametrize params (food: Food)

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +            if f.name == consumed_food.name and consumed_quantity == f.quantity:
we can increase performance having food as a dict of food with key = FoodType and value = quantity of that food type

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def food_availability(self, new_date):
parametrize

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def food_availability(self, new_date):
and why `new_date` and not just `date`?

2025-01-20 19:53 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def get_quantity_and_name(self):
what is this?

2025-01-20 19:53 UTC, bigliolimatteo commented on test/generic_food_storage_test.py
> +sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
wtf is this?

2025-01-20 21:34 UTC, laragazzadelsole commented on requirements.txt
> +black==24.10.0
Deleted

2025-01-23 10:25 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +class GenericFood:
I have added the decorator

2025-01-23 10:32 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +        if expiration_date >= purchase_date:
assert keyword used to replace if statements

2025-01-23 11:11 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +    def modify_quantity(cls, new_quantity):
I have replaced all attributes with @property decorator and setters. I am not sure it's what you meant, but at least I tried

2025-01-23 11:12 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +        return food
idk seemed better to save it in a variable u.u

2025-01-23 11:28 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +    def __init__(self, name: str, capacity: float, foods: list):
It really depends on how we are going to define capacity I think, number of fridge compartments? in kg? I think it's something we'll understand later, so for now I would leave it as float if you agree

2025-01-23 11:37 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +        if capacity > 0:
I added an assert line

2025-01-23 11:42 UTC, laragazzadelsole commented on requirements.txt
> +click==8.1.8
u.u

2025-01-23 11:42 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +class GenericFood:
Ok

2025-01-23 11:42 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +        if expiration_date >= purchase_date:
Done

2025-01-23 11:43 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +    def reduce_capacity(self, consumed_quantity):
As above, I don't know if I understood correctly what you meant, but at least I tried

2025-01-23 12:02 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +        for f in new_food:
Why is that a problem? I mean the idea is to store as much as food as possible until storage is full no? Also, I believe it is a very rare possibility that we buy so much food that we have no storage space at all.

2025-01-23 13:17 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +        for f in new_food:
I check now if if self.capacity >= total_quantity: however it depends on how we will define capacity

2025-01-23 13:37 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +    def food_availability(self, new_date):
ehmmmm

2025-01-23 13:49 UTC, laragazzadelsole commented on test/generic_food_storage_test.py
> +sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
It is necessary to include the parent directory of the current script. It is manipulating the sys path list, to determine the directories to search for modules when importing. Without it I get the following: ModuleNotFoundError: No module named 'generic_classes'

2025-01-27 09:10 UTC, bigliolimatteo requested changes

2025-01-27 09:10 UTC, bigliolimatteo commented on generic_classes/generic_food.py
> +    def name(self, value):
if you put "value" without params to every setter I think we are losing the actual benefit of having a setter :( I guess it should be something like `def name(self, name: String):`

2025-01-27 09:10 UTC, bigliolimatteo commented on generic_classes/generic_food.py
> +    @quantity.setter
how is this different from the function below?

2025-01-27 09:10 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def name(self, value):
same as before

2025-01-27 09:10 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def consume_food(self, consumed_food: dict["food":str, "quantity":float]):
+ I would limit quantity to be an Int, otherwise it becomes a lot difficult to manage

2025-01-27 11:13 UTC, laragazzadelsole commented on test/generic_food_storage_test.py
> +sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
I moved the test folder in the same directory of the code, but it doesn't work without that line of code :/
Maybe we can look at it together?

2025-01-27 12:20 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +    def name(self, value):
I am still not getting what are the benefits of having a setter I think

2025-01-27 12:25 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +            consumed_foodtype = consumed_food.get("food")
Yes makes more sense

2025-01-28 09:36 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +    @quantity.setter
The one above is the getter the one below is the setter

2025-01-28 10:40 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +    quantity: float
Why? the storage is only the container no? We are interested in the quantity of each food not in the total quantity no?

2025-01-28 10:43 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +            consumed_foodtype = consumed_food.get("food")
Done

2025-01-28 11:55 UTC, bigliolimatteo requested changes

2025-01-28 11:55 UTC, bigliolimatteo commented on generic_classes/generic_food.py
> +    quantity: float
yes but if we keep `quantity` as a property of the food in case we increase its quantity (e.g. we buy one more banana) we should go into the food and modify its quantity 🤔 

If you think about it at the end this is more the class defining the food type, while its the storage that actually needs to know how much of a specific food type it had stored

2025-01-28 11:55 UTC, bigliolimatteo commented on generic_classes/generic_food.py
> +    @quantity.setter
nope, I mean the difference between the quantity setter and the function called `modify_quantity` below at line 48 🤔  

Basically the two functions at like 44 and 48 are the same 🤔

2025-01-28 11:55 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def get_name(self) -> str:
if the class is not a dataclass its not needed I think to have this `get_xxx` methods 🤔  we can just say 
```
storage = new GenericFoodStorage(...)
storage.name
```

2025-01-28 11:55 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def add_food(self, new_food):
??

2025-01-28 11:55 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +        self._foods = list(foods)
this is still a list? 🤔  why?

2025-01-28 11:55 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +        food = self._foods[self._foods.index(food_to_consume)]
why this? 🤔  we can just make `self._foods` a dict

2025-01-28 11:55 UTC, bigliolimatteo commented on tests/test_generic_food_storage.py
> +# Add the parent directory of 'generic_classes' to the Python path
[just move tests inside the generic classes folder so this is not needed](https://stackoverflow.com/questions/61151/where-do-the-python-unit-tests-go)

2025-01-28 14:26 UTC, laragazzadelsole commented on generic_classes/generic_food.py
> +    @quantity.setter
Oh true 🫣

2025-01-28 14:28 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +    def consume_food(self, consumed_food: dict["food":str, "quantity":float]):
Done, but left float

2025-01-28 14:30 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +    def get_name(self) -> str:
True

2025-01-29 11:48 UTC, laragazzadelsole commented on tests/test_generic_food_storage.py
> +# Add the parent directory of 'generic_classes' to the Python path
I still have the same issue, also moving them in the same folder

2025-01-29 11:52 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +    def add_food(self, new_food):
Done

2025-01-29 16:30 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +                self.reduce_capacity(f.quantity)
Done

2025-01-29 16:31 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +    def consume_food(self, consumed_food, consumed_quantity):
Done

2025-02-04 15:57 UTC, bigliolimatteo requested changes

2025-02-04 15:57 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +        self, food: GenericFood, quantity: int, food_volume: int
quantity should be a float

2025-02-04 15:57 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +    def add_food(
what do you think about joining this and the previous function? 

Like we have only one "add food" function that checks if food is already there

If its already there just increase quantity, otherwise add food

2025-02-04 15:57 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +        return {
this I like a lot.

2025-02-04 15:57 UTC, bigliolimatteo commented on generic_classes/tests/test_generic_food.py
> +        banana = GenericFood(_name="Banana", _expiration_date=datetime(2024, 12, 10))
uh nonono can we use `name` and `expiration_date` without `_`? 🤔  otherwise setter is not used

2025-02-04 15:57 UTC, bigliolimatteo commented on generic_classes/tests/test_generic_food.py
> +        self.assertEqual(banana._name, "Banana")
```suggestion
        self.assertEqual(banana.name, "Banana")
```

2025-02-04 15:57 UTC, bigliolimatteo commented on generic_classes/tests/test_generic_food.py
> +        self.assertEqual(banana._expiration_date, datetime(2024, 12, 10))
```suggestion
        self.assertEqual(banana.expiration_date, datetime(2024, 12, 10))
```

2025-02-04 15:57 UTC, bigliolimatteo commented on generic_classes/tests/test_generic_food_storage.py
> +            _name="Banana", _expiration_date=datetime(2024, 12, 10)
remove `_` everywhere in tests ahah

2025-02-05 08:25 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +        self, food: GenericFood, quantity: int, food_volume: int
Changed

2025-02-05 08:25 UTC, laragazzadelsole commented on generic_classes/generic_food_storage.py
> +    def add_food(
Yes Sir

2025-02-05 08:52 UTC, laragazzadelsole commented on generic_classes/tests/test_generic_food.py
> +        banana = GenericFood(_name="Banana", _expiration_date=datetime(2024, 12, 10))
TypeError: GenericFood.__init__() got an unexpected keyword argument 'name'

2025-02-05 10:26 UTC, laragazzadelsole commented on generic_classes/tests/test_generic_food.py
> +        banana = GenericFood(_name="Banana", _expiration_date=datetime(2024, 12, 10))
Ok :)

2025-02-05 10:26 UTC, laragazzadelsole commented on generic_classes/tests/test_generic_food_storage.py
> +            _name="Banana", _expiration_date=datetime(2024, 12, 10)
Done

2025-02-05 10:35 UTC, bigliolimatteo requested changes

2025-02-05 10:35 UTC, bigliolimatteo commented on generic_classes/generic_food_storage.py
> +        food_volume: int,
what is this and why is it different from capacity?

2025-02-05 10:35 UTC, bigliolimatteo commented on generic_classes/tests/test_generic_food.py
> +sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
this we need to find a way to remove it ahah do you want to try or should I try?

2025-02-14 15:12 UTC, bigliolimatteo approved these changes

2025-02-14 15:13 UTC, merged